# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-06 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_logo',
            field=models.BooleanField(default=False),
        ),
    ]
