# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20170706_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
