# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_movie_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='Catagory',
        ),
        migrations.AddField(
            model_name='movie',
            name='Director',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='movie',
            name='Praducer',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
